### ISSUE TITLE
Add instance group for SITS (errand)

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#120]
Following tasks must be performed:

- Make required changes in [SITS bosh release](https://github.com/SUSE/sync-integration-tests-release) for kubecf. 
- Add ops files for SITS similar to smoke and brains.
- Add a bazel target to run them.

**Comment by bikramnehra** [comment]
`post-publish` pipeline is currently sitting at: https://concourse.suse.dev/teams/main/pipelines/post-publish

SITS release(must be renamed to `sync-integration-tests-release`): https://github.com/SUSE/sync-tests-release

**Comment by bikramnehra** [comment]
WIP for integration with kubecf at: https://github.com/SUSE/kubecf/tree/bisingh/add-sits

Also, the SITS bosh release needs some grooming to make it work with kubecf, WIP: https://github.com/SUSE/sync-integration-tests-release/tree/bisingh/fix-naming
