### ISSUE TITLE
Run "frozen" operator in post-publish pipeline.

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#123]
We have 2 pipelines for kubecf at the moment.
- pre-publish (hosted on gitlab, that gates PRs and publishes helm charts once tests pass on master)
- post-publish (hosted on Concourse, that runs more test scenarios for multiple kube versions and configurations)

In the post-publish pipeline, we should run the operator build that's referenced in kubecf.

**Comment by viovanov** [comment]
ping @mudler

**Comment by viovanov** [comment]
blocked by #124

**Comment by f0rmiga** [comment]
https://github.com/SUSE/kubecf/issues/124 is resolved. Unblocking this issue.

**Comment by mudler** [comment]
This should be fixed with https://github.com/SUSE/catapult/pull/76
