### ISSUE TITLE
Operator version should be discoverable inside the tarball released by the gitlab pipeline

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#124]
**Is your feature request related to a problem? Please describe.**
There's no easy way to tell which operator should be used with which kubecf build.

**Describe the solution you'd like**
There should be machine-readable information in the tarball released by the pipeline.

**Describe alternatives you've considered**
- reading the commit id from the pipeline
- cloning the repo at the commit
- parsing the bazel def file to get the version

**Additional context**
Needed to chain pipelines together nicely

**Comment by viovanov** [comment]
ping @f0rmiga

**Comment by f0rmiga** [comment]
@viovanov We could add cf-operator as a subchart.

**Comment by mook-as** [comment]
If we do a subchart, it would have to be deployed in the same namespace, right? (That might be fine, of course…)

**Comment by mook-as** [comment]
Hmm. Given that cf-operator (currently) defines its CRDs in code, we can't really subchart it, because
- By the time the BOSHDeployment is created (by helm), the subchart hasn't finished deploying yet (but it has _started_)
- Which means we will fail to deploy:
> `error: unable to recognize "dev/kubecf/rendered_template.yaml": no matches for kind "BOSHDeployment" in version "fissile.cloudfoundry.org/v1alpha1"`

**Comment by fargozhu** [comment]
#149
