### ISSUE TITLE
'configure-eirini'-job fails

### ISSUE THREAD

**Issue by jkbschmid** [SUSE/kubecf#150]
**Describe the bug**
The configure-eirini job fails.
```
kubecf-configure-eirini-3a14e0f3965d1e1c-kg8zl   0/2     CrashLoopBackOff   4          3m31s
```
The only container that fails is `configure-eirini-scf-configure-eirini`:
```
$ kubectl logs -n kubecf kubecf-configure-eirini-3a14e0f3965d1e1c-kg8zl -c configure-eirini-scf-configure-eirini

Configuring Eirini
Error from server (AlreadyExists): secrets "eirini-staging-secret" already exists

Copying Bits registry certificate on the host
The DaemonSet "eirini-copy-certs" is invalid: spec.template.spec.containers[0].image: Required value
```
The first error should already be fixed upstream (see https://github.com/cloudfoundry-community/eirini-bosh-release/pull/61), while the second issue is likely an error in kubecf.

**To Reproduce**
Run cf-operator master (e5d49c17cc206e5d379902327a12f7247ccc0eaa) with kubecf.

**Expected behavior**
Expected job should either not fail or not run at all.

**Comment by f0rmiga** [comment]
Thanks for reporting this. It was fixed in https://github.com/SUSE/kubecf/pull/140.
