### ISSUE TITLE
Bump to eirini 1.0

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#151]
**Is your feature request related to a problem? Please describe.**
We should support the latest stable release for eirini

**Describe the solution you'd like**
Bump eirini in the eirini-bosh-release, then bump the release image in kubecf.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jimmykarily** [comment]
We are working on that here: https://github.com/cloudfoundry-community/eirini-bosh-release/pull/70

we still need to change the eirini-persi and eirini-ssh extensions to use the right labels. We already did that on eirini-loggregator-bridge.
