### ISSUE TITLE
Instance group `database` cannot be scaled 

### ISSUE THREAD

**Issue by c0d1ngm0nk3y** [SUSE/kubecf#155]
**Describe the bug**
When trying to scale the deployment `database`, the result does not work. The org 'system' is sometimes not available. It seems that the databases are not replicated.

This is most likely related to `enable=false` in `deploy/helm/kubecf/assets/operations/instance_groups/database.yaml`. Is there a reason for this? Is this known behaviour?

**To Reproduce**
Scale the `instance_group` `database` to 2 and try `cf push` at least 5 times for the default org 'system'

**Expected behavior**
It should use a replicated database cluster. 

**Additional context**

https://github.com/cloudfoundry/cf-mysql-release/blob/develop/jobs/mysql/spec#L257

**Comment by f0rmiga** [comment]
This is the expected behaviour with cf-mysql-release. See my comment here: https://github.com/SUSE/kubecf/issues/79#issuecomment-555891207.
