### ISSUE TITLE
Add sle15 stack

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#156]
**Describe the solution you'd like**

Add the https://github.com/suse/cf-sle15-release containing the sle15 stack.

**Additional context**

The sle15 stack is needed by the SUSE buildpacks.

**Comment by bikramnehra** [comment]
@troytop @viovanov Some questions:
- Do we want to keep `sle15` stack available out-of-the-box or optionally? 
- What should be the default stack for apps in `kubecf` - `cflinuxfs3` or `sle15`?

**Comment by troytop** [comment]
For the upstream work (i.e. this repo eventually) the default should be `cflinuxfs3`. To change this to `sle15` would require consensus from all the other CF stakeholders, which is not there yet.

It should be non-controvertial to add `sle15` as long as `cflinuxfs3` remains the default in this repo.

**Comment by bikramnehra** [comment]
Refer: https://github.com/SUSE/scf/pull/2176 for changes needed in order to add `sle15` stack.

WIP at: https://github.com/SUSE/kubecf/tree/bisingh/add-sle15-stack

**Comment by bikramnehra** [comment]
Blocked on : https://github.com/SUSE/kubecf/issues/171

**Comment by fargozhu** [comment]
@troytop this card is just to add the stack and not make it the default. Can we proceed with it?

**Comment by bikramnehra** [comment]
PR: https://github.com/SUSE/kubecf/pull/260
