### ISSUE TITLE
Support TLS with external database

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#191]
**Is your feature request related to a problem? Please describe.**

Following up on https://github.com/SUSE/kubecf/issues/4, we should be able to use an external database with TLS enabled.

**Describe the solution you'd like**

Be able to enable the external database using TLS using Helm.

**Describe alternatives you've considered**

To have a conditional rendering of the disabling bits for TLS on the `database.yaml` ops-file that respects what the operator specified in the helm values.

**Additional context**

The original external database ops-files disable the TLS unconditionally.

**Comment by f0rmiga** [comment]
As seen on https://github.com/SUSE/kubecf/issues/257, there is more demand for this feature.

**Comment by qu1queee** [comment]
@f0rmiga we can help you with this, while we also need it. Ping me in slack, to define an ETA for it :)

**Comment by edwardstudy** [comment]
@f0rmiga Thx. It's urgent because database service requires TLS on IBM Cloud.

**Comment by fargozhu** [comment]
@qu1queee awesome!! This one is not even under the radar for the next two milestones but it will be a nice one to have. Thanks for the support.
