### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#23]
Sources should be linted

- [x] for yaml files
- [x] for scripts
- [ ] for helm templates after helm building the helm chart, with `helm lint`

**Comment by viovanov** [comment]
Maybe use https://github.com/adrienverge/yamllint ?

**Comment by viccuad** [comment]
An example of using yamllint and shellcheck, skipping some folders, and in posix standard:
https://github.com/SUSE/catapult/blob/master/tests/lint.sh

**Comment by viccuad** [comment]
Progress in add-yaml-linting branch.

**Comment by viccuad** [comment]
The linting script with yamllint is in place, but I'm having trouble installing yamllint with bazel. I have tried with https://github.com/bazelbuild/rules_python and things in the shape of the following, and a requirements.txt with yamllint, with no luck so far:

```
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.1/rules_python-0.0.1.tar.gz",
    sha256 = "aa96a691d3a8177f3215b14b0edc9641787abaaa30363a080165d06ab65e1161",
)
load('@rules_python//python:pip.bzl', 'pip_import')

pip_import(
    name = "yamllint",
    requirements = "//dev/linters:yamllint_requirements.txt",
)
load("@yamllint//:requirements.bzl", "pip_install")
pip_install()
```

**Comment by viccuad** [comment]
Right now the viccuad/add-yaml-linting branch contains a solution that:

Adds bazel target `//dev/linters:yamllint` to install the yamllint python module.
Provides script `dev/linters/yamllint.sh` that lints all .{yaml,yml} files in the project, analogous to `dev/linters/shellcheck.sh`.
Updates gitlab-ci to use the new linter.

Bazel's pip_install() is refusing to install pip, so for testing I have a workaround commit that installs pip as a system package in the gitlab image.

To test:

    git checkout viccuad/add-yaml-linting
    gitlab-runner exec docker lint


TODO:
Find better workaround
Update doc/Contribute.md, doc/linters.md
Fix yaml errors detected by the linter

**Comment by viccuad** [comment]
One implementation of yaml linting (sans helm templates) at https://github.com/SUSE/kubecf/pull/161
