### ISSUE TITLE
Document usage of kind for development

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#232]
**Is your feature request related to a problem? Please describe.**

Many people use kind for development, but we don't have a good document for it as we do for Minikube.

**Describe the solution you'd like**

A document with the particularities of the kubecf configuration with kind.

**Comment by fargozhu** [comment]
@f0rmiga I think this is cover by #14.

**Comment by f0rmiga** [comment]
@fargozhu You are right. Thanks!
