### ISSUE TITLE
Bump to cf-deployment v12.6.0

### ISSUE THREAD

**Issue by jkbschmid** [SUSE/kubecf#245]
**Is your feature request related to a problem? Please describe.**
Cf-k8s-networking does not work in combination with kubecf, because the label selector  of the k8s services created by cf-k8s-networking does not match with the pod labels created by eirini. Therefore, no traffic can be routed to apps.

**Describe the solution you'd like**
In order to use cf-k8s-networking in combination with kubecf, a newer version of capi-release (1.87.0->1.88.0) is required. The new capi-release contains a version of cloud-controller-ng that sends additional fields in a DesireLRPRequest (see https://github.com/cloudfoundry/cloud_controller_ng/pull/1474), which allow eirini to set the correct pod labels.
Capi-release v1.88.0 can be included in kubecf by bumping cf-deployment to v12.6.0 or newer.
@loewenstein @viovanov

**Comment by fargozhu** [comment]
@jkbschmid in #229 we're planning to bump to 12.14 or even later.

**Comment by jkbschmid** [comment]
@fargozhu That's good to know, I didn't see that one :) Closing in favour of #229
