### ISSUE TITLE
Configurable storage classes

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#26]
Right now, we don't allow users to configure the storage class to be used for persistent volumes.
It should be exposed in `values.yaml` and altered using an ops file.

The instance groups' [`persistent_disk_type`](https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/examples/bosh-deployment/boshdeployment-with-persistent-disk.yaml#L31) needs to be set.

**Comment by jimmykarily** [comment]
To clarify, we need an ops files that will change [this value](https://github.com/cloudfoundry/cf-deployment/blob/v8.1.0/cf-deployment.yml#L395) to the name of the desired storage class.
