### ISSUE TITLE
LB instances not coming up on EKS

### ISSUE THREAD

**Issue by prabalsharma** [SUSE/kubecf#262]
**Describe the bug**
On EKS LB instances for kubecf-router-public = 0/3, kubecf-ssh-proxy-public=3/3 and kubecf-tcp-router-public=0/3
This looks similar to the issue we had with scf on EKS
https://documentation.suse.com/suse-cap/1.5.1/html/cap-guides/cha-cap-depl-eks.html#sec-cap-install-scf-eks
```
Before traffic is routed to EKS load balancers, health checks are performed on them. These health checks require access to ports on the tcp-router service, which are only opened by request via cf map-route and other associated commands.
Use kubectl patch to patch the tcp-router service to expose a port to the EKS load balancer so the health checks can be completed.
```

https://github.com/SUSE/cloudfoundry/wiki/Load-balancers-in-AWS-EKS#aws-eks-specific-issue-with-scfuaa-deployment-and-solution

**To Reproduce**
Deploy kubecf on EKS. Check LBs on EKS UI

**Expected behavior**
Post kubecf deployment check instances of LBs on AWS. All instances won't come up

**Environment**
 - cf-operator-v0.4.2-201.gc4ad274e.tgz 
 - kubecf-3.0.0-1f48733.tgz

**Comment by prabalsharma** [comment]
just to me clear, this is a CAP2 blocker

**Comment by f0rmiga** [comment]
Will be fixed by https://github.com/SUSE/kubecf/pull/300 and https://github.com/SUSE/kubecf/pull/301.

**Comment by f0rmiga** [comment]
Fixed on https://github.com/SUSE/kubecf/commit/58399a370a4bc809a2f7c603c2922fbc054dd292 and https://github.com/SUSE/kubecf/commit/f82059dc86cd9d7700f34919dfc7999bba09eadd.
