### ISSUE TITLE
Command to get cluster-cidr fails

### ISSUE THREAD

**Issue by drnic** [SUSE/kubecf#292]
**Describe the bug**

The v0.1 release instructions request I get the cluster CIDR:

```
kubectl cluster-info dump --output yaml | awk 'match($0, /cluster-cidr=(.*)/, cidr) { print cidr[1] }'
```

But this gives me the following error:

```
awk: syntax error at source line 1
 context is
	match($0, >>>  /cluster-cidr=(.*)/, <<<
awk: bailing out at source line 1
```

I can see the `cluster-cidr` values:

```
kubectl cluster-info dump --output yaml | grep cluster-cidr
        --cluster-cidr=10.48.0.0/14 --resource-container="" --oom-score-adj=-998 --v=2
        --cluster-cidr=10.48.0.0/14 --resource-container="" --oom-score-adj=-998 --v=2
        --cluster-cidr=10.48.0.0/14 --resource-container="" --oom-score-adj=-998 --v=2
```

I'm on MacOS 10.14.6, and tested on zsh5 and bash5.

**Comment by f0rmiga** [comment]
This happens because this syntax is particular to gawk, which is the default on Linux. On OS X, you will need to install gawk, it can be done with homebrew. I'll update the release notes to reflect that.

**Comment by f0rmiga** [comment]
@drnic I'll close this. If you face any other issues related to awk on Mac, please feel free to reopen this issue.
