### ISSUE TITLE
GKE cluster-info does not specify --service-cluster-ip-range

### ISSUE THREAD

**Issue by drnic** [SUSE/kubecf#293]
**Describe the bug**

The v0.1 release notes ask me to search thru cluster-info for `--service-cluster-ip-range` value, but my GKE cluster does not seem to explicitly declare this. Probably because GKE clusters have a shared control plane and do not run their own kube-apiserver.

Is there another way to look up the `--service-cluster-ip-range` value you're looking for?

**Comment by drnic** [comment]
I guess a workaround is to look at existing service ClusterIPs and borrow the first two digits?

Thus my cluster's `service_cluster_ip_range` would be `10.52.0.0`?
```
kubectl get svc -n kube-system
NAME                   TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default-http-backend   NodePort    10.52.6.150    <none>        80:31605/TCP    64m
heapster               ClusterIP   10.52.5.94     <none>        80/TCP          64m
kube-dns               ClusterIP   10.52.0.10     <none>        53/UDP,53/TCP   64m
metrics-server         ClusterIP   10.52.14.124   <none>        443/TCP         64m
tiller-deploy          ClusterIP   10.52.4.97     <none>        44134/TCP       47m
```

**Comment by fargozhu** [comment]
@drnic you can also use the below command to get both cluster and service IP range from a GKE cluster
```
gcloud container clusters describe kubecf-faceless-14 | grep -i cidr
clusterIpv4Cidr: 10.32.0.0/14
  clusterIpv4Cidr: 10.32.0.0/14
  clusterIpv4CidrBlock: 10.32.0.0/14
  servicesIpv4Cidr: 10.97.0.0/20
  servicesIpv4CidrBlock: 10.97.0.0/20
  podIpv4CidrSize: 24
servicesIpv4Cidr: 10.97.0.0/20
```

**Comment by drnic** [comment]
@fargozhu awesome thanks for that
