### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#295]
**Is your feature request related to a problem? Please describe.**
As more people start to play with kubecf, we should state which K8s versions we know that we work on, along with any possible prerequisites or system requirements to guide new adopters.

**Describe the solution you'd like**
Update the parent README with the system requirements tied to Kubernetes versions supported. At some point, we should start taking the material in https://github.com/SUSE/kubecf/blob/master/doc/dev/ and make it easier to find.

**Comment by andreas-kupries** [comment]
JIRA: https://jira.suse.com/browse/CAP-1199

**Comment by andreas-kupries** [comment]
Done with #368 .
