### ISSUE TITLE
Document how to obtain k8s --cluster-cidr and --service-cluster-ip-range values for different platforms

### ISSUE THREAD

**Issue by f0rmiga** [SUSE/kubecf#297]
**Is your feature request related to a problem? Please describe.**

Different platforms will require `--cluster-cidr` and `--service-cluster-ip-range` values to be obtained using different means.

**Describe the solution you'd like**

A document that explains how to obtain these values for each of the following platforms:
- GKE
- EKS
- AKS
- CaaSP

**Additional context**

These values are passed to `helm` in order to allow CC to create the security groups that allow app internal communication to other CF components.

**Comment by fargozhu** [comment]
this is something that we could automate in the future to improve product usability.

**Comment by f0rmiga** [comment]
Replaced by https://github.com/SUSE/kubecf/issues/304.
