### ISSUE TITLE
Create klog.sh equivalent for kubecf for support information

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#303]
**Is your feature request related to a problem? Please describe.**
For scf, we have a tool to help with support cases called klog.sh: https://github.com/SUSE/scf/blob/develop/container-host-files/opt/scf/bin/klog.sh

We need an equivalent for kubecf, whereby we can see cluster information, IPs, logs, pods and other information to help troubleshoot product issues. This is important for testing and support since we would get an archive with all the appropriate files needed to identify what happened to a cluster without having access to it.

**Describe the solution you'd like**
At first, a port over of the scf bits. Over time, we should look at features that reflect useful information since there is cruft from previous architecture.

**Comment by f0rmiga** [comment]
@mook-as I assigned you here to reflect the SUSE Jira ticket that we have.

**Comment by f0rmiga** [comment]
No further changes required.
