### ISSUE TITLE
Add instance group for brain tests (errand)

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#31]
We need an ops file that adds an instance group as an errand, for running the brain tests.
Please look at how we do smoke tests as an example.

**Comment by jimmykarily** [comment]
Are we talking about these tests? https://github.com/SUSE/scf/tree/develop/src/scf-release/src/acceptance-tests-brain/test-scripts

If yes, shouldn't they be extracted to a separate repository first?

**Comment by andreas-kupries** [comment]
@jimmykarily This seems to have been done as https://github.com/SUSE/kubecf/issues/54 with https://github.com/SUSE/brain-tests-release as result.

**Comment by andreas-kupries** [comment]
Associated PR is https://github.com/SUSE/kubecf/pull/217
Ready for review.
See also https://jira.suse.com/browse/CAP-520

**Comment by andreas-kupries** [comment]
PR is merged. Commit = 8c416121cddc8d18fb03e08caec33fe98ee699a9.
Off to done.
