### ISSUE TITLE
Add autoscaler to release images

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#34]
The intent of this task to make the [app-autoscaler-release](https://github.com/cloudfoundry/app-autoscaler-release) images available in upstream and suse docker registry. Currently we are using app-autoscaler `v1.2.1` in [scf](https://github.com/SUSE/scf/blob/develop/container-host-files/etc/scf/config/role-manifest.yml#L170-L173), therefore we must build images for all releases from this version onward.

This task can be divided in two parts:

1. Adding autoscaler release to the [upstream](https://github.com/cloudfoundry-incubator/cf-operator-ci/blob/master/pipelines/release-images) pipelines. The upstream pipelines are pushing to `cfcontainerization` org on DockerHub.

2. Adding autoscaler release to the [suse](https://github.com/SUSE/cf-ci/tree/develop/build-pipelines) pipelines. The suse pipelines are pushing images to `registry.suse.com/cap-staging` repo for now.

**Comment by f0rmiga** [comment]
We need this in order to get https://github.com/SUSE/kubecf/pull/127 using our images.

**Comment by bikramnehra** [comment]
Upstream pipelines PR: https://github.com/cloudfoundry-incubator/cf-operator-ci/pull/102
SUSE pipelines PR: https://github.com/SUSE/cf-ci/pull/343

**Comment by bikramnehra** [comment]
Both PRs merged moving to done.

**Comment by f0rmiga** [comment]
I can confirm that the final Docker image was created: https://hub.docker.com/r/cfcontainerization/app-autoscaler/tags.
