### ISSUE TITLE
Patches in InitContainers cannot be applied on restart

### ISSUE THREAD

**Issue by phil9909** [SUSE/kubecf#38]
**Describe the bug**

* Some patches modify files in an EmptyDir which persists across pod restarts.
* Changes applied by the patches cannot be applied more than once (non zero exit-code)

Therefore, pods can not recover from a crash.
Also, the "real" error message is shadowed by error logs from `patch`.

**To Reproduce**
Run cf-operator with `features.eirini=true` and (to avoid some other issues), use eirini version 0.17.0.
We suspect that the bug can also be reproduced in many other ways. To be exact every time a initContainer or container crashes after a patch has been applied (to a file inside an `emtpyDir`).

**Expected behavior**
Patches should not fail.
We should see the "real" error. 

**Logs**
```
Hmm... Looks like a normal diff to me...
Patching file /var/vcap/all-releases/jobs-src/eirini/eirini-loggregator-bridge/templates/bpm.yml.erb using Plan A...
Hunk SUSE/scf#1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file /var/vcap/all-releases/jobs-src/eirini/eirini-loggregator-bridge/templates/bpm.yml.erb.rej
done
```

**Environment**
 - v3-develop
 - Eirini

**Comment by f0rmiga** [comment]
Fixed by https://github.com/SUSE/kubecf/pull/56.
