### ISSUE TITLE
Docs - How to rotate a secret

### ISSUE THREAD

**Issue by drnic** [SUSE/kubecf#44]
I wanted a secret to be regenerated, its dependent templates to be regenerated, and the instance groups updated.

I assumed that I should just delete the `secret`, and cf-operator would recreate it, and proceed with the steps above. I didn't observe this happening. Then I tried deleting `extendedsecret` too (once I remembered it existed)

Next I tried re-running `helm upgrade` but that didn't trigger the process of `cf-operator` recreating the now missing secret, etc.

What are the steps to replace a missing secret/rotate + regenerate secrets?

Relates to https://cloudfoundry.slack.com/archives/C1BQKKNP4/p1570164123144700?thread_ts=1570095847.136700&cid=C1BQKKNP4 / @viovanov

**Comment by andreas-kupries** [comment]
Given my last comment on #45 the underlying issue may be fixed.
@drnic Would you be able to confirm that ?

**Comment by andreas-kupries** [comment]
Note: The [original doc reference](#issuecomment-538327770) seems to have moved to
https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/controllers/quarks_statefulset.md#restarting-on-config-change

There is also https://github.com/cloudfoundry-incubator/cf-operator/blob/master/docs/controllers/quarks_statefulset.md#automatic-restart-of-containers
which seems to contradict. Except this place looks to talk about `StatefulSets` and associated containers, whereas the first reference seems to be about  `QuarksStatefulSets` instead.

It is unclear how these two things interact.

@aduffeck @viovanov ? Any insights from the operator people ?

**Comment by drnic** [comment]
Thanks for the prompt @andreas-kupries 

I did get rotation working today, and wrote up a draft blog post https://starkandwayne.com/blog/p/0d7981e3-1d36-4c42-8a10-9a12960816b2/

Does this also work for you?

**Comment by andreas-kupries** [comment]
Thanks for the article. Will try it out here ASAP.

**Comment by andreas-kupries** [comment]
Unfortunately not. Operator sees and reacts to a new q-secret. It does not react to the rotation request.

**Comment by andreas-kupries** [comment]
See https://github.com/cloudfoundry-incubator/cf-operator/issues/800

**Comment by andreas-kupries** [comment]
Draft documentation written, under assumption that this is indeed a bug in the operator, and not in the process. See #374

**Comment by fargozhu** [comment]
@andreas-kupries @drnic I was able to rotate the secrets by adding the namespace when running the apply command, which is missing on @drnic article...

steps:
```
❯ kubectl get secret my-internal-secret -n kubecf -ojsonpath='{.data.password}' | base64 --decode
jILD8xRkbazaf7qQNccvKtNfP5aOHdArMIi1r10NdIKQNoR7Qk7dlhWXNfrbAdQC
```

```
❯ kubectl apply -f rotate-my-internal-secret.yaml -n kubecf
configmap/rotate-my-internal-secret created
```
```
❯ kubectl get secret my-internal-secret -n kubecf -ojsonpath='{.data.password}' | base64 --decode
1Bzic0BLnYEu4ahffEV7JPMeBpOsPs1bWcWTaLoJZTlLdQybBGtGyaSMa2tNajc6
```

**Comment by andreas-kupries** [comment]
Oh :bulb: Will verify here and then update the PR. Thanks for your testing and time.

**Comment by andreas-kupries** [comment]
Verified. Adding the `-n kubecf` to the rotation request makes it trigger properly. Update to docs to come ASAP.
