### ISSUE TITLE
cf push fails - droplet cannot be uploaded to registry and image can't be pulled - TLS error in bits service - Azure environment

### ISSUE THREAD

**Issue by maeddes** [SUSE/kubecf#46]
After cf push my pods are in an ImagePullBackOff state. I tried a nodejs and Java app with the same behaviour.
At the end of the cf push step I get the following error:

```
2019/10/07 21:07:40 uploader-started
   2019/10/07 21:07:40 droplet info: https://scf-api.scf:9091/v1/droplet/250b0d90-da3b-47c0-a921-7b435556dde8?cc-droplet-upload-uri=https://scf-api.scf:9023/internal/v4/droplets/250b0d90-da3b-47c0-a921-7b435556dde8/upload /out/droplet.tgz
   2019/10/07 21:07:47 uploader-done

Waiting for app to start...
Start unsuccessful
```

The call to "k get pods -n scf-eirini" shows

```
NAME                                 READY   STATUS             RESTARTS   AGE
pod/cf-nodejs-dev-df21c35124-0       0/1     ImagePullBackOff   0          36m
pod/cf-nodejs-pp2-dev-bb3bc63f65-0   0/1     ImagePullBackOff   0          52s
pod/css-demo-dev-4fd41a4ced-0        0/1     ImagePullBackOff   0          6h56m
```

All the components in the scf namespace appear to be deployed correctly. All in running state.
When I delete the pod and it restarts I can see the following error in the bits service:

```
scf-bits-v1-0 bits-service-bits-service {"level":"error","ts":1570482684.155724,"caller":"http/server.go:3010","msg":"http: TLS handshake error from 10.240.0.5:37504: remote error: tls: bad certificate"}
```

I have used a "standard" 2 node cluster in Microsoft Azure. Deployed through Web UI. All default settings.
```
helm upgrade --install --wait --namespace scf cf-operator vendor/cf-operator/deploy/helm/cf-operator/ --set image.tag=v0.4.1-60.g642832d0 --set provider=gke
helm upgrade --install --wait --namespace scf scf https://scf-v3.s3.amazonaws.com/scf-3.0.0-8f7a71d1.tgz --set system_domain=scf.suse.dev --set features.eirini=true
```

Expected behaviour is a running app. The same helm commands have been applied to a GKE cluster successfully

**Comment by viovanov** [comment]
This is a problem on some EKS clusters as well.
When using a certificate signed by the kube, we require that the nodes trust the Kube CA.
If that's not the case, the nodes can't trust the bits service registry.

Can you please give us more details on the type of Azure environment you're working on?

**Comment by viovanov** [comment]
@drnic can you tell us if you've seen issues on your Azure runs?

I've created this table to help us figure out where this feature is available:
https://github.com/SUSE/kubecf/blob/master/INSTALL.md#eirini

**Comment by maeddes** [comment]
> This is a problem on some EKS clusters as well.
> When using a certificate signed by the kube, we require that the nodes trust the Kube CA.
> If that's not the case, the nodes can't trust the bits service registry.
> 
> Can you please give us more details on the type of Azure environment you're working on?

It's a 3 node AKS cluster, Kubernetes version 1.15.4. Created through the CLI with default settings.
I can provide any detail info or try to give you access. Just let me know what you need, thanks!

**Comment by maeddes** [comment]
I guess we can close this issue. I created a new cluster and used the latest version of Nic' script and the error is gone.
Kubernetes 1.15.4
--> Using cf-operator-v0.4.2+85.gc6d71da5.tgz
--> Using scf-3.0.0-c656daa.tgz
