### ISSUE TITLE
Bump to cf-deployment v12.4.0

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#49]
**Is your feature request related to a problem? Please describe.**
Current version 8 is quite old.

**Describe the solution you'd like**
Bump to cf-deployment v12.4.0

**Tasks**
- [ ] update the docker image release pipeline to contain this version
- [ ] update kubecf

**Comment by loewenstein** [comment]
Is there an eta for this?

**Comment by aduffeck** [comment]
@loewenstein I'd hope to finish this next week, but there could still be unforeseeen issues popping up, of course, since there are several moving parts involved.

The current state is this:

![image](https://user-images.githubusercontent.com/203813/69249189-c4f72380-0bad-11ea-8ae0-e36851984f2b.png)

**Comment by jimmykarily** [comment]
This PR adds the root CA in the certificates generated through CSRs : https://github.com/cloudfoundry-incubator/cf-operator/pull/726 this allows the bits service to start properly (to also get Eirini to work).
