### ISSUE TITLE
Add SCF Brain Tests to release images

### ISSUE THREAD

**Issue by gaktive** [SUSE/kubecf#54]
We have to add this [BOSH release](https://github.com/SUSE/scf/tree/develop/src/scf-release) to the list of BOSH releases that we build, in [this pipeline](https://github.com/cloudfoundry-incubator/cf-operator-ci/blob/master/pipelines/release-images/pipeline.yml#L2-L6).

**Comment by viovanov** [comment]
Blocks #29

**Comment by aduffeck** [comment]
We split the existing BOSH release into a [brain test](https://github.com/SUSE/brain-tests-release) and a [sync tests](https://github.com/SUSE/sync-tests-release) one. Both are being built by [the](https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/release-images/jobs/build-brain-tests/builds/1) [pipeline](https://ci.flintstone.cf.cloud.ibm.com/teams/quarks/pipelines/release-images/jobs/build-sync-tests/builds/1) now.
