### ISSUE TITLE
kubecf releases not available via github releases

### ISSUE THREAD

**Issue by drnic** [SUSE/kubecf#7]
The v3.0.0 release from https://github.com/SUSE/scf/tree/v3-develop does not appear under https://github.com/SUSE/scf/releases, nor is there a v3.0.0 tag on the git repo for commit 8f7a71d1 (as found in the release filename `scf-3.0.0-8f7a71d1.tgz`).

Will it or future v3 releases appear here with release notes, please?

relates to SUSE/scf#2756

**Comment by viovanov** [comment]
We have the following:

- a pipeline: https://gitlab.com/susecf/kubecf/pipelines
- a bucket for releases: https://scf-v3.s3.amazonaws.com/index.html
- a way (not the best) to freeze the operator version: https://github.com/SUSE/kubecf/blob/master/.gitlab/pipelines/config/config.sh#L9

Given these 3, we can create a github release for a known version that works, with proper release notes, as a one-off.
There's another issue (#20) for describing this process.

**Comment by fargozhu** [comment]
@viovanov add both **cf-operator** and **kubecf** packages as assets into the release itself would be enough?

**Comment by f0rmiga** [comment]
It's released. :)
