### ISSUE TITLE
Fix pxc-release so it's not dependent on monit

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#79]
We want to use [pxc-release](https://github.com/cloudfoundry-incubator/pxc-release) but it currently uses monit, and we don't have monit anymore in Kube-land.

https://github.com/cloudfoundry-incubator/galera-healthcheck/tree/5f062bf290ca6f6853fe06205bda99bf615dc332/monit_client

**Tasks**

- [ ] open an issue upstream
- [ ] talk to the upstream team (slack \#mysql-galera)
- [ ] open a PR

**Comment by f0rmiga** [comment]
Using pxc-release with kubecf proved impractical. Not only it is dependent on monit, but other issues were noticed:
- The mysql daemon is started in the pre-start script, calling bpm: https://github.com/cloudfoundry-incubator/pxc-release/blob/f55c4982979fc4c5d5707a872072c0d5fa7e4728/jobs/pxc-mysql/templates/pre-start.sh.erb#L138-L156.
- The cluster-health-logger pre-start tries to talk to mysql, assuming it was started on the pre-start script mentioned above: https://github.com/cloudfoundry-incubator/pxc-release/blob/f55c4982979fc4c5d5707a872072c0d5fa7e4728/jobs/cluster-health-logger/templates/setup.erb. The setup that this pre-start performs would need to be executed on the main container, therefore replacing https://github.com/cloudfoundry-incubator/pxc-release/blob/f55c4982979fc4c5d5707a872072c0d5fa7e4728/jobs/cluster-health-logger/templates/bpm.yml.erb#L4.

Other issues may exist that we cannot foresee yet.

**Comment by loewenstein** [comment]
@f0rmiga interesting. How is our way forward with regards to database then?
@c0d1ngm0nk3y noticed that the [mysql galera database cannot be scaled](https://github.com/SUSE/kubecf/issues/155), apparently [on purpose](https://github.com/SUSE/kubecf/blob/master/deploy/helm/kubecf/assets/operations/instance_groups/database.yaml#L40).

So for production we would strongly recommend the use of an external database? 

cc @viovanov @troytop

**Comment by f0rmiga** [comment]
@loewenstein For the pre-release of kubecf we will keep cf-mysql-release in SA mode and promote the use of an external database: https://github.com/SUSE/kubecf/pull/162. When I added the database instance group, I purposedly made it SA to simplify the setup at the time and allow us to move forward with other instance groups. Given that cf-mysql-release is scheduled for deprecation, I don't believe the effort to write and maintain the BPM manifest for all jobs is justifiable. Please, let me know what you think.

**Comment by loewenstein** [comment]
@f0rmiga sounds fine, just wanted to make sure it's a conscious decision. Care to comment in #155  and close it?
