### ISSUE TITLE
Run CATs as part of CI

### ISSUE THREAD

**Issue by viovanov** [SUSE/kubecf#8]
Run the Cloud Foundry Acceptance Tests as part of [our pipeline](https://gitlab.com/susecf/kubecf/pipelines).

This is not about making everything green, just run it. We'll likely have follow up issues for green-ness.

**Comment by jimmykarily** [comment]
@mook-as have you already started with this?

**Comment by mook-as** [comment]
@jimmykarily I've started on getting CATS to _run_, but I haven't started on doing any CI yet.

**Comment by gaktive** [comment]
Moving to icebox until we get CATS passing. Fixing those issues take precedence :)

**Comment by gaktive** [comment]
Once we get CATS to pass, let's make sure we run all tests on both Diego and Eirini deployments. @f0rmiga is already aware based on recent conversation.

**Comment by f0rmiga** [comment]
Implemented on https://github.com/SUSE/kubecf/pull/209.
