### ISSUE TITLE
"redirected you too many times" - login not possible

### ISSUE THREAD

**Issue by bkrannich** [SUSE/kubecf#85]
I am running `v0.4.2%2B92.gd053b0ec` from https://cf-operators.s3.amazonaws.com/helm-charts/index.html as well as `3.0.0-6e03f97` from https://scf-v3.s3.amazonaws.com/index.html.

Deploying this combination, I have an issue during login to CF. Tracing this down, I am getting
```
This page isn’t working login.<domain> redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```
in Chrome for `login.<domain>`.

To fix this, the workaround I was introduced to is to add the following into my `values.yaml`:
```
properties:
  uaa:
    uaa:
      uaa:
        require_https: false
```

It looks to me that this behavior is flapping between working and not working, I didn't need this additional configuration with prior combinations of cf-operator and KubeCF.

**Comment by bkrannich** [comment]
My guess is that #106 resolves this issue and explain why I got it.

**Comment by mook-as** [comment]
@bkrannich Given that #106 has now been closed (since we resolved the configuration issue), does this still need to stay open?

**Comment by bkrannich** [comment]
@mook-as: Yes, #106 sounds like the issue is specific to our Gardener setup. So, let's close this one for now.
